-- MySQL Script generated by MySQL Workbench
-- Thu Aug  1 17:56:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema betting-league
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema betting-league
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `betting-league` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `betting-league` ;

-- -----------------------------------------------------
-- Table `betting-league`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betting-league`.`teams` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `abbr` VARCHAR(10) NOT NULL,
  `full_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `betting-league`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betting-league`.`games` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `home_team_id` BIGINT UNSIGNED NOT NULL,
  `away_team_id` BIGINT UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `week` BIGINT NOT NULL,
  `home_open_spread` DECIMAL(8,2) NOT NULL,
  `home_curr_spread` DECIMAL(8,2) NOT NULL,
  `game_started` TINYINT(1) NOT NULL,
  `home_points` INT NULL DEFAULT NULL,
  `away_points` INT NULL DEFAULT NULL,
  `spread_winner` ENUM('home', 'away', 'push') NULL DEFAULT NULL,
  `away_open_spread` DECIMAL(8,2) NOT NULL,
  `away_curr_spread` DECIMAL(8,2) NOT NULL,
  `home_ml_odds` DECIMAL(8,2) NOT NULL,
  `away_ml_odds` DECIMAL(8,2) NOT NULL,
  `game_open_total` DECIMAL(8,2) NOT NULL,
  `game_curr_total` DECIMAL(8,2) NOT NULL,
  `game_over_odds` DECIMAL(8,2) NOT NULL,
  `game_under_odds` DECIMAL(8,2) NOT NULL,
  `api_id` VARCHAR(255) NULL DEFAULT NULL,
  `game_completed` TINYINT(1) NULL DEFAULT '0',
  `game_start_time` DATETIME NULL DEFAULT NULL,
  `nfl_year` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `api_id` (`api_id` ASC) VISIBLE,
  INDEX `games_home_team_id_foreign` (`home_team_id` ASC) VISIBLE,
  INDEX `games_away_team_id_foreign` (`away_team_id` ASC) VISIBLE,
  CONSTRAINT `games_away_team_id_foreign`
    FOREIGN KEY (`away_team_id`)
    REFERENCES `betting-league`.`teams` (`id`),
  CONSTRAINT `games_home_team_id_foreign`
    FOREIGN KEY (`home_team_id`)
    REFERENCES `betting-league`.`teams` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 273
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `betting-league`.`leagues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betting-league`.`leagues` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `type` ENUM('league', 'pickem', 'survivor') NOT NULL,
  `sport` ENUM('nfl', 'nhl', 'nba', 'mlb', 'mls', 'pl') NOT NULL,
  `year` YEAR NOT NULL,
  `weekly_points` BIGINT NULL DEFAULT NULL,
  `games_select_min` BIGINT NULL DEFAULT NULL,
  `games_select_max` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `betting-league`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betting-league`.`users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `role` ENUM('admin', 'user') NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `betting-league`.`league_statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betting-league`.`league_statistics` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `league_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `games_selected` INT NOT NULL,
  `average_points` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `league_statistics_league_id_foreign` (`league_id` ASC) VISIBLE,
  INDEX `league_statistics_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `league_statistics_league_id_foreign`
    FOREIGN KEY (`league_id`)
    REFERENCES `betting-league`.`leagues` (`id`),
  CONSTRAINT `league_statistics_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `betting-league`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `betting-league`.`leagues_have_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betting-league`.`leagues_have_users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `league_id` BIGINT UNSIGNED NOT NULL,
  `league_role` ENUM('commish', 'cocommish', 'owner', 'coowner') NOT NULL,
  `team_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `leagues_have_users_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `leagues_have_users_league_id_foreign` (`league_id` ASC) VISIBLE,
  CONSTRAINT `leagues_have_users_league_id_foreign`
    FOREIGN KEY (`league_id`)
    REFERENCES `betting-league`.`leagues` (`id`),
  CONSTRAINT `leagues_have_users_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `betting-league`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `betting-league`.`team_statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betting-league`.`team_statistics` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `team_id` BIGINT UNSIGNED NOT NULL,
  `year` YEAR NOT NULL,
  `spread_losses` INT NOT NULL,
  `spread_wins` INT NOT NULL,
  `spread_pushes` INT NOT NULL,
  `h_under_wins` INT NOT NULL,
  `h_fav_wins` INT NOT NULL,
  `a_under_wins` INT NOT NULL,
  `a_fav_wins` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `team_statistics_team_id_foreign` (`team_id` ASC) VISIBLE,
  CONSTRAINT `team_statistics_team_id_foreign`
    FOREIGN KEY (`team_id`)
    REFERENCES `betting-league`.`teams` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `betting-league`.`users_have_scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betting-league`.`users_have_scores` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `league_id` BIGINT UNSIGNED NOT NULL,
  `week` BIGINT NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `points` INT NOT NULL,
  `perfect` TINYINT(1) NOT NULL,
  `overdog_correct` INT NOT NULL,
  `underdog_correct` INT NOT NULL,
  `curr_streak` BIGINT NULL DEFAULT NULL,
  `max_streak` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_have_scores_league_id_foreign` (`league_id` ASC) VISIBLE,
  INDEX `users_have_scores_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `users_have_scores_league_id_foreign`
    FOREIGN KEY (`league_id`)
    REFERENCES `betting-league`.`leagues` (`id`),
  CONSTRAINT `users_have_scores_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `betting-league`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `betting-league`.`users_select_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betting-league`.`users_select_games` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `league_id` BIGINT UNSIGNED NOT NULL,
  `game_id` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `points` BIGINT NOT NULL,
  `team_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `week` BIGINT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_select_games_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `users_select_games_game_id_foreign` (`game_id` ASC) VISIBLE,
  INDEX `users_select_games_league_id_foreign` (`league_id` ASC) VISIBLE,
  INDEX `team_id` (`team_id` ASC) VISIBLE,
  CONSTRAINT `users_select_games_game_id_foreign`
    FOREIGN KEY (`game_id`)
    REFERENCES `betting-league`.`games` (`id`),
  CONSTRAINT `users_select_games_ibfk_1`
    FOREIGN KEY (`team_id`)
    REFERENCES `betting-league`.`teams` (`id`),
  CONSTRAINT `users_select_games_league_id_foreign`
    FOREIGN KEY (`league_id`)
    REFERENCES `betting-league`.`leagues` (`id`),
  CONSTRAINT `users_select_games_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `betting-league`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
